version: '3.3'

services:
  postgres_db:
    container_name: postgresdb
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgres/data/
volumes:
  postgres_data:
